PY=python


tests:
	$(PY) e1_tests.py
	$(PY) e3_tests.py
	$(PY) es_tests.py
	$(PY) kdf_tests.py
	$(PY) mkdf_tests.py

es:
	$(PY) es.py

es-tests:
	$(PY) es_tests.py

e1:
	$(PY) e1.py

e1-tests:
	$(PY) e1_tests.py

e3:
	$(PY) e3.py

e3-tests:
	$(PY) e3_tests.py

kdf:
	$(PY) kdf.py

kdf-tests:
	$(PY) kdf_tests.py

mkdf:
	$(PY) mkdf.py

mkdf-tests:
	$(PY) mkdf_tests.py
